# Generated by Django 3.0.11 on 2021-02-04 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_from', models.CharField(max_length=255)),
                ('send_to', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=30)),
                ('enc_message', models.BinaryField()),
                ('private_key', models.FileField(upload_to='priv_key')),
                ('pub_key', models.FileField(upload_to='pub_key')),
                ('enc_key_ntru', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['send_to', 'create_at'],
            },
        ),
    ]
